import json

# Mapping for Option table
option_mapping = {
    'contract_id': ['c_contractSymbol', 'p_contractSymbol'],
    'underlying': ['underlying_x', 'underlying_y'],
    'expiration_date': ['ExpDate'],
    'strike': ['Strike'],
    'option_type': lambda row: 'call' if row['c_contractSymbol'].endswith('C') else 'put',
    'contract_size': ['contract_size_x', 'contract_size_y'],
    'description': ['description_x', 'description_y'],
    'expiration_type': ['expiration_type_x', 'expiration_type_y'],
    'exch': ['exch_x', 'exch_y'],
}
#
# # Mapping for OptionQuote table
# option_quote_mapping = {
#     'contract_id': ['c_contractSymbol', 'p_contractSymbol'],
#     'root_symbol': ['root_symbol_x', 'root_symbol_y'],
#     'fetch_timestamp': ['timestamp'],  # Assuming this is the fetch timestamp
#     'last': ['Call_LastPrice', 'Put_LastPrice'],
#     'change': ['c_change', 'p_change'],
#     'volume': ['Call_Volume', 'Put_Volume'],
#     'open': ['open_x', 'open_y'],
#     'high': ['high_x', 'high_y'],
#     'low': ['low_x', 'low_y'],
#     'close': ['close_x', 'close_y'],
#     'bid': ['c_bid', 'p_bid'],
#     'ask': ['c_ask', 'p_ask'],
#     # 'greeks': lambda row: json.dumps({
#     #     'delta': float(row.get('c_delta', row.get('p_delta', 0))),
#     #     'gamma': float(row.get('c_gamma', row.get('p_gamma', 0))),
#     #     'theta': float(row.get('c_theta', row.get('p_theta', 0))),
#     #     'vega': float(row.get('c_vega', row.get('p_vega', 0))),
#     #     'rho': float(row.get('c_rho', row.get('p_rho', 0))),
#     #     'implied_volatility': float(row.get('Call_IV', row.get('Put_IV', 0)))
#     # }),
#     'greeks': ['p_greeks', 'c_greeks'],
#     'change_percentage': ['Call_PercentChange', 'p_percentChange'],
#     'average_volume': ['average_volume_x', 'average_volume_y'],
#     'last_volume': ['last_volume_x', 'last_volume_y'],
#     'trade_date': ['c_lastTrade', 'p_lastTrade'],
#     'prevclose': ['prevclose_x', 'prevclose_y'],
#     'week_52_high': ['week_52_high_x', 'week_52_high_y'],
#     'week_52_low': ['week_52_low_x', 'week_52_low_y'],
#     'bidsize': ['bidsize_x', 'bidsize_y'],
#     'bidexch': ['bidexch_x', 'bidexch_y'],
#     'bid_date': ['bid_date_x', 'bid_date_y'],
#     'asksize': ['asksize_x', 'asksize_y'],
#     'askexch': ['askexch_x', 'askexch_y'],
#     'ask_date': ['ask_date_x', 'ask_date_y'],
#     'open_interest': ['Call_OI', 'Put_OI'],
# }
option_quote_mapping = {
    'contract_id': ['c_contractSymbol', 'p_contractSymbol'],
    'root_symbol': ['root_symbol_x', 'root_symbol_y'],
    'fetch_timestamp': ['timestamp'],
    'last': ['Call_LastPrice', 'Put_LastPrice'],
    'change': ['c_change', 'p_change'],
    'volume': ['Call_Volume', 'Put_Volume'],
    'open': ['open_x', 'open_y'],
    'high': ['high_x', 'high_y'],
    'low': ['low_x', 'low_y'],
    'close': ['close_x', 'close_y'],
    'bid': ['c_bid', 'p_bid'],
    'ask': ['c_ask', 'p_ask'],
    'greeks': ['p_greeks', 'c_greeks'],
    'change_percentage': ['Call_PercentChange', 'p_percentChange'],
    'average_volume': ['average_volume_x', 'average_volume_y'],
    'last_volume': ['last_volume_x', 'last_volume_y'],
    'trade_date': ['c_lastTrade', 'p_lastTrade'],
    'prevclose': ['prevclose_x', 'prevclose_y'],
    'week_52_high': ['week_52_high_x', 'week_52_high_y'],
    'week_52_low': ['week_52_low_x', 'week_52_low_y'],
    'bidsize': ['bidsize_x', 'bidsize_y'],
    'bidexch': ['bidexch_x', 'bidexch_y'],
    'bid_date': ['bid_date_x', 'bid_date_y'],
    'asksize': ['asksize_x', 'asksize_y'],
    'askexch': ['askexch_x', 'askexch_y'],
    'ask_date': ['ask_date_x', 'ask_date_y'],
    'open_interest': ['Call_OI', 'Put_OI'],
}
# Updated SymbolQuote mapping
# Updated SymbolQuote mapping
symbol_quote_mapping = {
    'symbol_name': lambda row: row['symbol'] if 'symbol' in row else 'SPY',
    'fetch_timestamp': ['timestamp'],
    'last_trade_price': ['Current Stock Price', 'CurrentPrice', 'last'],
    'current_bid': ['bid'],
    'current_ask': ['ask'],
    'daily_open': ['open', 'Open'],
    'daily_high': ['high', 'High'],
    'daily_low': ['low', 'Low'],
    'previous_close': ['LAC', 'prevclose'],
    'last_trade_volume': ['last_volume'],
    # 'daily_volume': ['volume', 'Volume'],
    'average_daily_volume': ['average_volume'],
    'last_trade_timestamp': ['trade_date', 'timestamp'],
    'week_52_high': ['week_52_high'],
    'week_52_low': ['week_52_low'],
    'daily_change': ['change'],
    'daily_change_percentage': ['change_percentage', 'Current SP % Change(LAC)'],
    'current_bidsize': ['bidsize'],
    'bidexch': ['bidexch'],
    'current_bid_date': ['bid_date'],
    'current_asksize': ['asksize'],
    'askexch': ['askexch'],
    'current_ask_date': ['ask_date'],
    'exch': ['exch'],
    # Timesales data
    'last_1min_timestamp': ['timestamp'],

    'last_1min_timesale': ['time'],
    'last_1min_open': ['open'],
    'last_1min_high': ['high'],
    'last_1min_low': ['low'],
    'last_1min_close': ['close'],
    'last_1min_volume': ['volume'],
    'last_1min_vwap': ['vwap'],
}


# Updated TechnicalAnalysis mapping
technical_analysis_mapping = {
    'symbol_name': lambda row: 'SPY',  # Assuming this is for SPY data
    'fetch_timestamp': ['timestamp', 'CurrentTime:'],
    'price_1min': ['price_1min', 'price'],
    'open_1min': ['open_1min', 'open'],
    'high_1min': ['high_1min', 'high'],
    'low_1min': ['low_1min', 'low'],
    'close_1min': ['close_1min', 'close'],
    'volume_1min': ['volume_1min', 'volume'],
    'vwap_1min': ['vwap_1min', 'vwap'],
    'SMA_20_1min': ['SMA_20_1min', 'SMA_20'],
    'RSI_2_1min': ['RSI2'],
    'RSI_7_1min': ['RSI7'],
    'RSI_14_1min': ['RSI14', 'RSI'],
    'EMA_50_1min': ['EMA_50'],
    'EMA_200_1min': ['EMA_200'],
    'MACD_12_26_1min': ['MACD_12_26_1min', 'MACD'],
    'Signal_Line_12_26_1min': ['Signal_Line_12_26_1min', 'Signal_Line'],
    'AwesomeOsc_1min': ['AwesomeOsc', 'AwesomeOsc_1min'],
    'ADX_1min': ['ADX', 'ADX_1min'],
    'CCI_1min': ['CCI', 'CCI_1min'],
    'Williams_R_1min': ['Williams_R', 'Williams_R_1min'],
    'PVO_1min': ['PVO', 'PVO_1min'],
    'PPO_1min': ['PPO', 'PPO_1min'],
    'CMF_1min': ['CMF', 'CMF_1min'],
    'OBV_1min': ['OBV', 'OBV_1min'],
    'MFI_1min': ['MFI', 'MFI_1min'],
    'Keltner_Upper_1min': ['Keltner_Upper', 'Keltner_Upper_1min'],
    'Keltner_Lower_1min': ['Keltner_Lower', 'Keltner_Lower_1min'],
    'BB_high_20_1min': ['BB_high_20_1min'],
    'BB_mid_20_1min': ['BB_mid_20_1min'],
    'BB_low_20_1min': ['BB_low_20_1min'],
    'VPT_1min': ['VPT', 'VPT_1min'],
    # Add mappings for 5min and 15min intervals
    'SMA_20_5min': ['SMA_20_5min'],
    'SMA_20_15min': ['SMA_20_15min'],
    'MACD_12_26_5min': ['MACD_12_26_5min'],
    'MACD_12_26_15min': ['MACD_12_26_15min'],
    'Signal_Line_12_26_5min': ['Signal_Line_12_26_5min'],
    'Signal_Line_12_26_15min': ['Signal_Line_12_26_15min'],
    # ... add other 5min and 15min fields as needed
}

# Updated ProcessedOptionData mapping
processed_option_data_mapping = {
    'symbol_name': lambda row: 'SPY',  # Assuming this is for SPY data
    'fetch_timestamp': ['timestamp', 'CurrentTime:'],
    'exp_date': ['ExpDate'],
    'current_stock_price': ['Current Stock Price', 'CurrentPrice'],
    'current_sp_change_lac': ['Current SP % Change(LAC)'],
    'maximumpain': ['Maximum Pain'],
    'bonsai_ratio': ['Bonsai Ratio'],
    'bonsai_ratio_2': ['Bonsai Ratio 2'],
    'b1_dividedby_b2': ['B1/B2'],
    'b2_dividedby_b1': ['B2/B1'],
    'pcr_vol': ['PCR-Vol'],
    'pcr_oi': ['PCR-OI'],
    'pcrv_up1': ['PCRv Up1'],
    'pcrv_up2': ['PCRv Up2'],
    'pcrv_up3': ['PCRv Up3'],
    'pcrv_up4': ['PCRv Up4'],
    'pcrv_down1': ['PCRv Down1'],
    'pcrv_down2': ['PCRv Down2'],
    'pcrv_down3': ['PCRv Down3'],
    'pcrv_down4': ['PCRv Down4'],
    'pcroi_up1': ['PCRoi Up1'],
    'pcroi_up2': ['PCRoi Up2'],
    'pcroi_up3': ['PCRoi Up3'],
    'pcroi_up4': ['PCRoi Up4'],
    'pcroi_down1': ['PCRoi Down1'],
    'pcroi_down2': ['PCRoi Down2'],
    'pcroi_down3': ['PCRoi Down3'],
    'pcroi_down4': ['PCRoi Down4'],
    'itm_pcr_vol': ['ITM PCR-Vol'],
    'itm_pcr_oi': ['ITM PCR-OI'],
    'itm_pcrv_up1': ['ITM PCRv Up1'],
    'itm_pcrv_up2': ['ITM PCRv Up2'],
    'itm_pcrv_up3': ['ITM PCRv Up3'],
    'itm_pcrv_up4': ['ITM PCRv Up4'],
    'itm_pcrv_down1': ['ITM PCRv Down1'],
    'itm_pcrv_down2': ['ITM PCRv Down2'],
    'itm_pcrv_down3': ['ITM PCRv Down3'],
    'itm_pcrv_down4': ['ITM PCRv Down4'],
    'itm_pcroi_up1': ['ITM PCRoi Up1'],
    'itm_pcroi_up2': ['ITM PCRoi Up2'],
    'itm_pcroi_up3': ['ITM PCRoi Up3'],
    'itm_pcroi_up4': ['ITM PCRoi Up4'],
    'itm_pcroi_down1': ['ITM PCRoi Down1'],
    'itm_pcroi_down2': ['ITM PCRoi Down2'],
    'itm_pcroi_down3': ['ITM PCRoi Down3'],
    'itm_pcroi_down4': ['ITM PCRoi Down4'],
    'itm_oi': ['ITM OI'],
    'total_oi': ['Total OI'],
    'itm_contracts_percent': ['ITM Contracts %'],
    'net_iv': ['Net_IV'],
    'net_itm_iv': ['Net ITM IV'],
    'net_iv_mp': ['Net IV MP'],
    'net_iv_lac': ['Net IV LAC'],
    'niv_current_strike': ['NIV Current Strike'],
    'niv_1higher_strike': ['NIV 1Higher Strike'],
    'niv_1lower_strike': ['NIV 1Lower Strike'],
    'niv_2higher_strike': ['NIV 2Higher Strike'],
    'niv_2lower_strike': ['NIV 2Lower Strike'],
    'niv_3higher_strike': ['NIV 3Higher Strike'],
    'niv_3lower_strike': ['NIV 3Lower Strike'],
    'niv_4higher_strike': ['NIV 4Higher Strike'],
    'niv_4lower_strike': ['NIV 4Lower Strike'],
    'niv_highers_minus_lowers1thru2': ['NIV highers(-)lowers1-2'],
    'niv_highers_minus_lowers1thru4': ['NIV highers(-)lowers1-4'],
    'niv_1thru2_avg_percent_from_mean': ['NIV 1-2 % from mean'],
    'niv_1thru4_avg_percent_from_mean': ['NIV 1-4 % from mean'],
    'niv_dividedby_oi': ['Net_IV/OI'],
    'itm_avg_niv_dividedby_itm_oi': ['Net ITM_IV/ITM_OI'],
    'closest_strike_to_cp': ['Closest Strike to CP'],
}