model:
  chosen_predictors:
    - 'Bonsai Ratio'
    - 'Bonsai Ratio 2'
    - 'PCRv Up1'
    - 'PCRv Down1'
    - 'ITM PCR-Vol'
    - 'Net IV LAC'
  study_name: '20min_05pt'
  device: 'cuda'  # Use 'cpu' if CUDA not available

training:
  cells_forward_to_check: 20
  threshold_cells_up: 2  # 20 * 0.1
  percent_down: 0.05
  anticondition_threshold_cells: 20  # cells_forward_to_check * 1
  threshold_down: 0.5

optuna:
  n_trials: 100  # Adjust as needed

save:
  prompt_for_saving: True

data:
  df_filename: "../../../../data/historical_multiday_minute_DF/SPY_historical_multiday_min.csv"